apiVersion: batch/v1
kind: Job
metadata:
  name: hello1
spec:
  template:
    # 这里是 Pod 模板
    spec:
      containers:
        - name: hello
          image: ubuntu:latest
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello2
spec:
  template:
    # 这里是 Pod 模板
    spec:
      containers:
        - name: hello2
          image: ubuntu:latest
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: Never